name: Test Storybook

on: [push]

jobs:
  test-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install corepack latest
        run: npm install -g corepack@latest
      - name: Corepack enable
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: 'package.json'
          cache: pnpm
      - name: Cache node modules
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache Playwright
        id: cache-playwright
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            playwright-${{ runner.os }}-
      - name: Setup Playwright
        run: pnpm exec playwright install --with-deps
        if: ${{ steps.cache-playwright.outputs.cache-hit != 'true' }}
      - name: Build Storybook
        run: pnpm build-storybook
      - name: Run Storybook Server
        run: pnpm dlx http-server storybook-static --port 6006 --silent &
      - name: Test Storybook
        run: pnpm dlx wait-on http://127.0.0.1:6006 && pnpm test-storybook --junit
